[workspace]
members = [
    "hardfiskur_core",
    "hardfiskur_engine",
    "hardfiskur_uci",
    "hardfiskur_ui",
    "hardfiskur_app",

    "find_magics",
    "bitboard_attack_viewer",
    "perft",
    "perft_testsuite",
    "pst_viewer",
    "tuner-lib",
]
resolver = "2"
