[workspace]
members = [
    "hardfiskur_core",
    "hardfiskur_uci",
    "hardfiskur_ui",

    "hardfiskur",

    "find_magics",
    "bitboard_attack_viewer",
    "perft",
    "perft_testsuite", "hardfiskur_engine",
]
resolver = "2"
