[package]
name = "hardfiskur_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.28"
hardfiskur_core = { path = "../hardfiskur_core" }
image = "0.25"
