[package]
name = "hardfiskur_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
hardfiskur_core = { path = "../hardfiskur_core" }
zerocopy = "0.7"

[dev-dependencies]
pretty_assertions = "1.4.0"