[package]
name = "hardfiskur_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
hardfiskur_core = { path = "../hardfiskur_core" }
zerocopy = { version = "0.8", features = ["alloc"] }
zerocopy-derive = "0.8"

[dev-dependencies]
pretty_assertions = "1.4.0"
