[package]
name = "find_magics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hardfiskur_core = { path = "../hardfiskur_core" }
rand = "0.8.5"
