[package]
name = "pst_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28"
hardfiskur_core = { path = "../hardfiskur_core" }
hardfiskur_engine = { path = "../hardfiskur_engine" }
