[package]
name = "hardfiskur_uci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
nom = "7.1"
nom_permutation = "0.1"
hardfiskur_core = { path = "../hardfiskur_core" }
